CREATE TABLE `h_user` (
  `id` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_id` INT(11) NOT NULL COMMENT '工号',
  user_name VARCHAR(20) NOT NULL COMMENT '姓名',
  user_password VARCHAR(50) NOT NULL COMMENT '密码',
  sex VARCHAR(2) COMMENT '性别',
  ic_card VARCHAR(18) COMMENT '身份证号',
  address VARCHAR(30) COMMENT '家庭住址',
  phone VARCHAR(11) NOT NULL COMMENT '电话号码',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `h_positioning` (
  `id` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `equipment_id` INT(20) NOT NULL COMMENT '设备id',
  equipment_lognitude FLOAT(10) NOT NULL COMMENT '设备经度',
  equipment_latitude FLOAT(10) NOT NULL COMMENT '设备纬度',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;



CREATE TABLE `h_equipment` (
  `id` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `equipment_id` int(20) NOT NULL COMMENT '设备id',
  user_id int(10) NOT NULL COMMENT '用户id',
  equipment_number VARCHAR(50) NOT NULL COMMENT '设备编号',
  equipment_name VARCHAR(20) COMMENT '设备名',
  equipment_data VARCHAR(18) COMMENT '设备生产日器',
  equipment_place VARCHAR(30) COMMENT '设备生产地址',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `h_fence` (
  `id` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `fence_id` INT(11) NOT NULL COMMENT '围栏id',
  fence_number VARCHAR(20) NOT NULL COMMENT '围栏编号',
  fence_name VARCHAR(30) NOT NULL COMMENT '围栏名称',
  fence_node VARCHAR(50) COMMENT '围栏备注',
  fence_longitude float(18) COMMENT '围栏经度',
  fence_latitude float(10) COMMENT '围栏纬度',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `h_warning` (
  `id` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `warning_id` INT(11) NOT NULL COMMENT '警告id',
  waring_number VARCHAR(20) NOT NULL COMMENT '警告编号',
  waring_name VARCHAR(30) NOT NULL COMMENT '警告名称',
  waring_why VARCHAR(40) COMMENT '警告原因',
  waring_time VARCHAR(18) COMMENT '警告时间',
  shutdown_time VARCHAR(30) COMMENT '警告关闭时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;


CREATE TABLE `h_signRecord` (
  `id` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `equipment_id` INT(10) NOT NULL COMMENT '设备id',
  sing_id int(10) NOT NULL COMMENT '签到区域id',
  sing_number VARCHAR(30) NOT NULL COMMENT '签到区域编号',
  sign_name VARCHAR(50) COMMENT '签到区域名',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `h_temperature` (
  `id` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `user_id` INT(11) NOT NULL COMMENT '用户id',
  temperature_id int(20) NOT NULL COMMENT '体温记录id',
  temperature float(10) NOT NULL COMMENT '体温',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `h_hardwareData` (
  `id` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'id',
  data_id int(20) not null comment '数据记录id',
  acceleration_x int(10) not null comment '加速度x',
  acceleration_y INT(10) NOT NULL COMMENT '加速度y',
  acceleration_z INT(10) NOT NULL COMMENT '加速度z',
  pressure INT(10) NOT NULL COMMENT '压力',
  longitude INT(10) NOT NULL COMMENT '经度',
  latitude INT(10) NOT NULL COMMENT '纬度',
  temperature INT(10) NOT NULL COMMENT '体温',
  button INT(10) NOT NULL COMMENT '按钮',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;


